spring:
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost/testdb?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
      username: root
      password: 111111
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        query.in_clause_parameter_padding: true
        id.new_generator_mappings: false
    defer-datasource-initialization: true