#spring.cloud.openfeign.httpclient.hc5.enabled: true
# spring.cloud.openfeign.okhttp.enabled: true

open-feign:
  sample-url: fakerestapi.azurewebsites.net/api/v1/Users
  my-fake-url: localhost:8084/fake


logging:
  level:
    org.springframework.cloud.openfeign: TRACE
    feign: DEBUG
    feign.Client: TRACE
    feign.SynchronousMethodHandler: DEBUG
