management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    java.enabled: true
    os.enabled: true
    env.enabled: true # info 하위 항목 출력
    build.enabled: true
    git.mode: "full"

info:
  app:
    name: actuator-toy
    test: test

logging:
  level:
    com.toy.springactuator.controller: debug