services:
  mysql:
    image: mysql:8.4
    container_name: graalvm-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=springgraalvm
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p111111" ]
      interval: 5s
      timeout: 5s
      retries: 20
