server:
  port: 8100

spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  jpa.defer-datasource-initialization: true
#  sql.init.data-locations: classpath:data.sql

logging:
  level:
    "[org.springframework.web.filter]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
    "[com.toy.currencyconversionservice]": debug
  pattern:
    console: "[%d{HH:mm:ss}] [%thread] %clr([%-5level]) %class{0}.%M%clr(\\(%L\\)){magenta}| %msg%n"

