spring:
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: never
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
  output.ansi.enabled: always
logging:
  path: logs
#   level:
#     "[org.springframework.web.filter]": debug
#     "[org.hibernate.SQL]": debug
#     "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
#     "[com.toy]": debug

custom:
  number: 1

test-property.data: main-yml-config