### 가입
POST localhost:8080/members
Content-Type: application/json

{
  "email": "test3@gmail.com",
  "nickname": "test",
  "birthday": "2022-01-01"
}

### 조회
GET localhost:8080/members/5

### Nickname 수정
POST localhost:8080/members/1/nickname
Content-Type: application/json

{
  "nickname": "update-nickname"
}
