### 가입
POST localhost:8080/members
Content-Type: application/json

{
  "email": "test4@gmail.com",
  "nickname": "test4",
  "birthday": "2022-01-01"
}

### 조회
GET localhost:8080/members/5

### Nickname 수정
POST localhost:8080/members/8/nickname
Content-Type: application/json

{
  "nickname": "update-nickname"
}

### MemberNicknameHistory 조회
GET localhost:8080/members/8/histories


### 팔로우 하기
POST localhost:8080/follow/8/9


### 팔로우 한 member 목록조회
GET localhost:8080/follow/8