### 가입
POST localhost:8080/members
Content-Type: application/json

{
  "email": "test4@gmail.com",
  "nickname": "test4",
  "birthday": "2022-01-01"
}

### 조회
GET localhost:8080/members/5

### Nickname 수정
POST localhost:8080/members/8/nickname
Content-Type: application/json

{
  "nickname": "update-nickname"
}

### MemberNicknameHistory 조회
GET localhost:8080/members/8/histories


### 팔로우 하기
POST localhost:8080/follow/8/9


### 팔로우 한 member 목록조회
GET localhost:8080/follow/8


### 포스트 작성
POST localhost:8080/posts
Content-Type: application/json

{
  "memberId": 8,
  "content": "test-content-1"
}


### 일자별 포스트 생성 수
GET localhost:8080/posts/daily-post-counts?memberId=8&firstDate=2022-11-05&lastDate=2022-11-07