spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
