#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

rabbitmq:
  queue:
    name: test-queue
    json:
      name: json-queue
  exchange:
    name: test-exchange
  routing:
    key: test-key
    json:
      key: json-key