server:
  port: 8000

spring:
  rabbitmq:
    addresses: localhost
    host: localhost
    port: 15672
    username: guest
    password: guest
    connection-timeout: 5000
    management-uri: http://localhost:15672/


rabbitmq:
  queue:
    name: test-queue
    json:
      name: json-queue
  exchange:
    name: test-exchange
  routing:
    key: test-key
    json:
      key: json-key