/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

/**
 * Task 실행
 * gradle firstTask
 * gradle fT
 */
println("start")
task("firstTask") {
    println("firstTask run")
    doFirst {
        println("doFirst")
    }
    doLast {
        println("doLast")
    }
}
println("end")
