spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3308/fulltextsearch-test?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
      username: root
      password: 111111
  jpa:
    database: mysql
    open-in-view: false
    hibernate.ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: com.toy.jpafulltext.config.MySql8DialectCustom
  jpa.defer-datasource-initialization: true
  sql.init.mode: always
  sql.init.data-locations: classpath:data.sql

logging:
  level:
    "[org.springframework.web.filter]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
    "[com.toy]": debug