spring:
  graphql:
    schema:
      locations: classpath:graphql/lec14-error-handling
    path: /graphql
    websocket:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

logging.level.root: INFO