### test
POST localhost:8080/api/requeue
Content-Type: application/json

### test
POST localhost:8080/api/route
Content-Type: application/json

{
  "data": "test~",
  "type": "TYPE2"
}

### test
POST localhost:8080/api/split
Content-Type: application/json