spring:
  profiles:
    active:
      - local
    group:
      local: "site-local,db-local"
      dev: "site-dev,db-dev"
    include:
      - db
      - site

custom:
  random-value: "${random.value}"
  random-int: "${random.int}"
  random-long: "${random.long}"
  random-int-between: "${random.int[1000,9999]}"
  uuid: "${random.uuid}"