spring:
  thymeleaf:
    prefix: classpath:/static/templates/
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  h2:
    console:
      enabled: true
cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key}
      secretKey: ${aws_secret_key}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws-secret:
  access-key: ${aws_access_key}
  secret-key: ${aws_secret_key}

email:
  from-address: ${from_address}

logging:
  level:
    "[org.springframework.web.filter]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
    "[com.emailauthentication]": debug
