resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 100
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        record-failure-predicate: com.study.resilience4j.config.RestClientCircuitRecordFailurePredicate
        register-health-indicator: true

    instances:
      default:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
