resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 100
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
#        ignore-exception-predicate: com.study.resilience4j.config.RestClientCircuitIgnoreExceptionPredicate

# 최근 요청 n개를 대상으로 실패율 계산
# 실패율이 n% 이상인 경우 CLOSED -> OPEN
# OPEN 에서 10s 대기 후 OPEN -> HALF_OPEN
# HALF_OPEN 상태에서 n개 요청 모니터링. 실패율 초과하는 경우 HALF_OPEN -> OPEN 초과하지 않는 경우 HALF_OPEN -> CLOSED

    instances:
      default:
        base-config: default
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers # circuitbreakers: /actuator/circuitbreakers
