resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 100
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
        record-failure-predicate: com.study.resilience4j.config.RestClientCircuitRecordFailurePredicate

    instances:
      default:
        base-config: default
