resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 100
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5

    instances:
      default:
        base-config: default
