POST localhost:8081/api/users/testname

###

PUT localhost:8081/api/users/19723818-0388-43f9-b5d1-44197605ef5b/updatename5


###

DELETE localhost:8081/api/users/u1

###

GET localhost:8081/api/users/revision/u1/revisions

###

GET localhost:8081/api/users/revision/u1/last-change-revision

###

GET localhost:8081/api/users/revision/u1/revisions-by?createdDate=2023-02-10:00:00:00

###

POST localhost:8081/test/soft-delete
Content-Type: application/json

###

DELETE localhost:8081/test/soft-delete/f34ed47d-7b31-4915-a64c-42385845dbd1
