server:
  port: 8080

spring:
  application:
    name: spring-stomp
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:chat
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
