spring:
  thymeleaf:
    prefix: classpath:/static/templates/
    cache: false

cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key}
      secretKey: ${aws_secret_key}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws-secret:
  access-key: ${aws_access_key}
  secret-key: ${aws_secret_key}
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${google_mail_username}
#    password: ${google_mail_password} # gmail 앱 비밀번호
#    properties:
#      smtp.auth: true
#      smtp.starttls.enable: true
#      transport.protocol: smtp
#      mime.charset: utf-8

