spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google_mail_username}
    password: ${google_mail_password}

    properties:
      smtp.auth: true
      smtp.starttls.enable: true
      transport.protocol: smtp
      mime.charset: utf-8


