version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: "pharmacy-redis"
    image: redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-db:
    container_name: "pharmacy-mariadb"
    image: mariadb:10
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"