server:
  port: 8080

spring:
  application:
    name: configclient
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: "configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: refresh
