spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/root
    username: root
    password: root
  flyway:
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

flyway:
  url: jdbc:postgresql://localhost:5432/root
  username: root
  password: root

logging:
  level:
#    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
