spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${googleClentId}
            client-secret: ${googleClientSecret}
          naver:
            client-name: naver
            client-id: ${naverCleintId}
            client-secret: ${naverClientSecret}

custom:
  mailPersonalName: RFICE
  mailFromAddress: rfice@de.rfice.com
  max-byte-count: 16777216
  read-write-timeout-seconds: 30
  response-timeout-seconds: 30
  connect-timeout-millis: 3000
  max-idle-and-life-time-seconds: 18