version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    environment:
      - "TZ=Asia/Seoul"
    ports:
      - "8888:8080"
    volumes:
      - "./jenkins_data:/var/jenkins_home"