spring:
  batch:
    job:
      names: {job.name:NONE}
    initializa-schema: never

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost/batch-basic?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
      username: root
      password: 111111

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  jpa.defer-datasource-initialization: true
  sql.init.mode: never
  sql.init.data-locations: classpath:schema.sql

# spring.batch.job.names: {job.name:NONE}
# Program Arguments ? job.name=job_name ?? ?? ??

# spring.batch.initialize-schema
# never: batch meta table ?? X