server:
  port: 8083

springdoc:
  packages-to-scan:
    - com.study.swagger.controller
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui-custom.html
    disable-swagger-default-url: true
