spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/study
    username: sa
    password:
  mvcstatic-path-pattern: /webapp/**

file.path: ./files
