server:
  port: 8082

spring:
  application:
    name: test-service-2
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: config
      profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
