### 1. client credential accessToken request
POST http://localhost:8080/v1/oauth2/token
Authorization: Basic dGVzdENsaWVudElkOnRlc3RTZWNyZXQ=  # base64(testClientId:testSecret)
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

### 2. accessToken introspection
POST http://localhost:8080/oauth2/introspect
Authorization: Basic dGVzdENsaWVudElkOnRlc3RTZWNyZXQ=  # base64(testClientId:testSecret)
Content-Type: application/x-www-form-urlencoded

token=eyJraWQiOiJmYjM2MTc3My0wMTNhLTQzNGMtOTU1YS02ZmE4NjE3NjU1NTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0Q2xpZW50SWQiLCJhdWQiOiJ0ZXN0Q2xpZW50SWQiLCJuYmYiOjE3NTUxMjg1NzYsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImV4cCI6MTc1NTEzNTc3NiwiaWF0IjoxNzU1MTI4NTc2LCJqdGkiOiJkZDAyZDU2MS1jNjFjLTQ4NTItODIwMy1kOGIzYmNjMjQ3OTgifQ.LmqhYJ9FyI8kTFqD8fresy-wjL2aCQjQWY16Kk-Zcg1PUEWefqaVr0g3VU-blpc6YnM_BjB9AhN62Jyh7oZnRnrquxbPRWDu9AJtL_Wqe44zgrxYbwhHs86OOPXwVbCsGojhy9Ud-f1UXwXk0Nz9CNoZXxBMb7fAhIU-83LRLn7FQH8drKSr9Ru7p1_kmUwE6sm7O05RIcb4aWTf_6V1Nl7S_gVSJ5edtOHcwiTeuNkDXE93B_kMt9PKVOnioMb5TxOy_Ob6FXdzXeGkKAbVO7miAw2j4OGYe0esKUTT15xT6c0RaRdv-9YQrVaMBqsFlvzCdIGM6hWHM8fVrSmpdQ

###

### jwk set
GET http://localhost:8080/oauth2/jwks
Accept: application/json
