### signup
POST http://localhost:8901/api/v1/users/signup
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "test1234",
  "name": "test-name"
}

### signin
POST http://localhost:8901/api/v1/users/signin
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "test1234"
}

### logout
POST http://localhost:8901/api/v1/users/logout
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoiZGhraW0yIiwibmFtZSI6InRlc3QtbmFtZSIsImV4cCI6MTY2NDE3MjE0NSwiaWF0IjoxNjY0MTcyMTQ1LCJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdEBnbWFpbC5jb20ifQ.cEJgwQNWnoHLAlQQcQhTE-EA2Pq49w056TnaSbQQvNg