cloud:
  aws:
    stack.auto: false
    s3.bucket: test-bucket
    region.static: ap-northeast-2
    credentials:
      accessKey: ${awsAccessKey}
      secretKey: ${awsSecretKey}
s3:
  bucket: <your-bucket-name>
