spring:
  application:
    name: serviceA


management:
  tracing:
    sampling:
      probability: 1.0 # default: 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


logging:
  pattern:
    level: "[%X{traceId:-},%X{spanId:-}]"