spring:
  application:
    name: openfeign
  cloud:
    openfeign:
      httpclient:
        max-connections: 200 # 최대 connection pool 수 (default: 200)
        max-connections-per-route: 200 # 동일 호스트 대상 최대 connection pool 수 (default: 50)
        connection-timer-repeat: 3000 # idle connection, expiry connection 정리 주기 default: 3000ms
#        time-to-live: 900 # connection pool ttl. default: 900s, 실제 적용되지 않음. RequestConfig.connectionKeepAlive 가 사용됨.
        hc5:
          connection-request-timeout: 1 # lease request to connection pool timeout(minutes) (default: 3m)
          enabled: true # default: true
  threads:
    virtual:
      enabled: true
logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager: DEBUG
