spring:
  application:
    name: openfeign
  cloud:
    openfeign:
      httpclient:
        max-connections: 200 # ?? connection pool ? (default: 200)
        max-connections-per-route: 200 # ?? ???? ?? ??? ? ? ?? connection ? (default: 50)
        connection-timer-repeat: 3000 # idle connection ?? ?? default: 3000
        hc5:
          connection-request-timeout: 1 # connection lease ?? ? leased ??? ?? ??(minutes) (default: 3m)
logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager: DEBUG
