spring:
  application:
    name: concurrency
  datasource:
    url: jdbc:h2:mem:concurrency;DB_CLOSE_DELAY=-1;DEFAULT_LOCK_TIMEOUT=10000
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      "[hibernate.show_sql]": false
      "[hibernate.format_sql]": false
