server.port: 8899
spring:
#   rabbitmq:
#     addresses: localhost:5672
#     username: guest
#     password: guest
  cloud:
    function:
      destination: uppercase|reverse
    stream:
      bindings:
        uppercasereverse-in-0:
          destination: upper-string
          group: demo
        uppercasereverse-out-0:
          destination: reverse-string