  mariadb:
    container_name: "mariadb"
    image: mariadb:10.5.12
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - "3308:3306"
    volumes:
      - ./mariadb/custom-my.cnf:/etc/mysql/my.cnf
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--skip-character-set-client-handshake"
      - "--lower_case_table_names=0"