server.port: 8093
spring:
  data:
    mongodb:
      database: productdb
#       host: 10.11.12.13
#       port: 27107
#       username: username
#       password: password


de.flapdoodle.mongodb.embedded.version: 4.0.2