spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---

spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      data-locations: classpath:sql/data.sql
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: ALWAYS

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
