POST http://localhost:8091/products
Content-Type: application/json

{
  "description": "description1",
  "price": 1000
}

###

GET http://localhost:8091/products/643d18136086486614720fe8

###

GET http://localhost:8091/products

###

PUT http://localhost:8091/products/643d18136086486614720fe8
Content-Type: application/json

{
  "description": "update-description1",
  "price": 999
}

###

DELETE http://localhost:8091/products/643d18136086486614720fe8