spring:
  datasource:
#    url: jdbc:mysql://localhost/test?rewriteBatchedStatements=true&createDatabaseIfNotExist=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=99999
    url: jdbc:mariadb://localhost/test?rewriteBatchedStatements=true&createDatabaseIfNotExist=true
    username: root
    password: 111111
    hikari:
      maximum-pool-size: 30
      connection-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 100
