spring:
  datasource:
    url: jdbc:mariadb://localhost/test?createDatabaseIfNotExist=true
    username: root
    password: 111111
    hikari:
      maximum-pool-size: 30
      connection-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 100
logging:
  level:
    "[org.mariadb.jdbc]": trace