//user
POST localhost:8092/users
Content-Type: application/json

{
  "name": "kim",
  "balance": 10000
}

###
GET localhost:8092/users/1

###
GET localhost:8092/users

###
PUT localhost:8092/users/1
Content-Type: application/json

{
  "name": "kim-update",
  "balance": 9999
}

###
DELETE localhost:8092/users/1

//transaction
###
POST localhost:8092/users/transactions
Content-Type: application/json

{
  "userId": 1,
  "amount": 1000
}

###
GET localhost:8092/users/1/transactions