spring:
  exposed:
    generate-ddl: true
  datasource:
    master:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:test-master;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
    slave:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:test-slave;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      data-locations: classpath:sql/data.sql
logging:
  level:
    "[org.springframework.web.filter]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
    "[com.toy]": debug
