spring:
  datasource:
    hikari:
      master:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:13306/emoji-test?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
        username: root
        password: 111111
  jpa:
    database: mysql
    hibernate.ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        query.in_clause_parameter_padding: true
        id.new_generator_mappings: false