server:
  port: 8000

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan:
    - com.study.swagger.controller
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger
    disable-swagger-default-url: true
