spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true
    username: root
    password: "111111"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      "[hibernate.show_sql]": false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081
