server:
  port: ${PORT:8080}

spring:
  application:
    name: quartz-dynamic-scheduler
  datasource:
    url: jdbc:h2:file:./data/scheduler;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            isClustered: true
            clusterCheckinInterval: 5000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 5

logging:
  level:
    com.study.quartzscheduler: INFO
