spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true


  sql:
    init:
      data-locations: classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    "[org.springframework.web.filter]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace
    "[com.toy]": debug